import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { createClient } from "@/utils/supabase/server";
import { api } from "@/lib/trpc/api";
import { type Account, type User } from "@/components/providers/AuthProvider";
import { cookies } from "next/headers";
import TrpcProvider from "@/components/providers/TRPCProvider";
import AuthProvider from "@/components/providers/AuthProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	let user: User = null;
	let account: Account = null;

	const supabase = createClient();
	const { data } = await supabase.auth.getUser();
	user = data.user;

	if (user) {
		account = await api.account.getAccount.query();
	}

	return (
		<html lang="en">
			<body className={cn(inter.className, "h-screen w-screen")}>
				<AuthProvider user={user} account={account}>
					<TrpcProvider cookies={cookies().toString()}>

						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							enableSystem
							disableTransitionOnChange
						>
							{children}
						</ThemeProvider>
						<Toaster richColors />
					</TrpcProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
